export default function Head() {
  return (
    <>
      <title>Error Code: Coffee - A geeky podcast about tech, web dev and all things life</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='apple-touch-icon' sizes='180x180' href='/apple-touch-icon.png' />
      <link rel='icon' type='image/png' sizes='32x32' href='/favicon-32x32.png' />
      <link rel='icon' type='image/png' sizes='16x16' href='/favicon-16x16.png' />
      <link rel='manifest' href='/site.webmanifest' />
      <link rel='mask-icon' href='/safari-pinned-tab.svg' color='#7c52fe' />
      <meta name='msapplication-TileColor' content='#603cba' />
      <meta name='theme-color' content='#ffffff' />
    </>
  );
}
